name: Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  id-token: write 

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          package_json_file: ./package.json

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm build

      - run: pnpm test

      # Either opens/updates the "Version Packages" PR (if changesets exist),
      # or, when that PR is merged into main, publishes to npm.
      - name: Create Release PR or Publish
        uses: changesets/action@v1
        with:
          version: pnpm -s ci:version
          publish: pnpm -s release
          createGithubReleases: true
          commitMode: git-cli
          setupGitUser: true
          onlyPublishWithChangesets: true
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: 'true'
